"""auteur change

Revision ID: 0b134fa41f12
Revises: c596cddf8f5b
Create Date: 2025-05-18 19:31:20.380045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b134fa41f12'
down_revision = 'c596cddf8f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorie_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_categorie_label'), ['label'], unique=False)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auteur', sa.String(length=255), nullable=False))
        batch_op.create_index(batch_op.f('ix_document_auteur'), ['auteur'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_date_ajout'), ['date_ajout'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_titre'), ['titre'], unique=False)

    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paragraph_contenu'), ['contenu'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paragraph_contenu'))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_titre'))
        batch_op.drop_index(batch_op.f('ix_document_date_ajout'))
        batch_op.drop_index(batch_op.f('ix_document_auteur'))
        batch_op.drop_column('auteur')

    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorie_label'))
        batch_op.drop_index(batch_op.f('ix_categorie_description'))

    # ### end Alembic commands ###
