"""first migration

Revision ID: 0f62c39c7d73
Revises: 
Create Date: 2025-04-05 21:59:22.345961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f62c39c7d73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('Userid', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=30), nullable=False),
    sa.Column('motdepasse', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Userid')
    )
    op.create_table('categorie',
    sa.Column('CategorieId', sa.Integer(), nullable=False),
    sa.Column('motCle', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.Userid'], ),
    sa.PrimaryKeyConstraint('CategorieId')
    )
    op.create_table('document',
    sa.Column('DocumentId', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('date_ajout', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.Userid'], ),
    sa.PrimaryKeyConstraint('DocumentId')
    )
    op.create_table('paragraph',
    sa.Column('ParagrapheId', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.CategorieId'], ),
    sa.PrimaryKeyConstraint('ParagrapheId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paragraph')
    op.drop_table('document')
    op.drop_table('categorie')
    op.drop_table('user')
    # ### end Alembic commands ###
