"""change in doc and para model

Revision ID: 3acaa782b023
Revises: 4aea5dc1afc6
Create Date: 2025-04-26 18:53:04.413778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acaa782b023'
down_revision = '4aea5dc1afc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=255), nullable=False))
        batch_op.drop_column('motCle')

    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentId', sa.Integer(), nullable=False))
        batch_op.alter_column('categorie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'document', ['documentId'], ['DocumentId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('categorie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('documentId')

    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motCle', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('label')

    # ### end Alembic commands ###
