"""Add file_path to Document

Revision ID: 4aea5dc1afc6
Revises: 0f62c39c7d73
Create Date: 2025-04-10 23:47:27.002695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aea5dc1afc6'
down_revision = '0f62c39c7d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
