"""etablissement and status change

Revision ID: d332b8965094
Revises: 0b134fa41f12
Create Date: 2025-05-24 18:53:31.556973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd332b8965094'
down_revision = '0b134fa41f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etablissement', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.alter_column('motdepasse',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('motdepasse',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('etablissement')

    # ### end Alembic commands ###
